[2025-07-03T12:02:10.629+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: merge_query_to_temp_logs.run_merge_query manual__2025-07-03T12:02:09.415092+00:00 [queued]>
[2025-07-03T12:02:10.635+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: merge_query_to_temp_logs.run_merge_query manual__2025-07-03T12:02:09.415092+00:00 [queued]>
[2025-07-03T12:02:10.635+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-07-03T12:02:10.645+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_merge_query> on 2025-07-03 12:02:09.415092+00:00
[2025-07-03T12:02:10.651+0000] {standard_task_runner.py:60} INFO - Started process 9734 to run task
[2025-07-03T12:02:10.653+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'merge_query_to_temp_logs', 'run_merge_query', 'manual__2025-07-03T12:02:09.415092+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/merge_query_dag.py', '--cfg-path', '/tmp/tmp8hauqgsp']
[2025-07-03T12:02:10.654+0000] {standard_task_runner.py:88} INFO - Job 49: Subtask run_merge_query
[2025-07-03T12:02:10.693+0000] {task_command.py:423} INFO - Running <TaskInstance: merge_query_to_temp_logs.run_merge_query manual__2025-07-03T12:02:09.415092+00:00 [running]> on host 61fdbbb5a1a9
[2025-07-03T12:02:10.779+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='merge_query_to_temp_logs' AIRFLOW_CTX_TASK_ID='run_merge_query' AIRFLOW_CTX_EXECUTION_DATE='2025-07-03T12:02:09.415092+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-03T12:02:09.415092+00:00'
[2025-07-03T12:02:10.783+0000] {merge_query_dag.py:36} INFO - Executing 4 queries from the merged SQL file.
[2025-07-03T12:02:10.784+0000] {merge_query_dag.py:40} INFO - 
ðŸš€ Executing Query 1:
-- SELECT_QUERY_START
SELECT 
    PROJECT_ID, PROJECT_NAME, DEPARTMENT, START_DATE, END_DATE, BUDGET
FROM DEV_DB.DEV_SCHEMA.ATTENDANCE
WHERE START_DATE >= '2024-01-01'
ORDER BY START_DATE
[2025-07-03T12:02:10.791+0000] {base.py:83} INFO - Using connection ID 'snowflake_dev_conn' for task execution.
[2025-07-03T12:02:10.791+0000] {connection.py:370} INFO - Snowflake Connector for Python Version: 3.6.0, Python Version: 3.8.18, Platform: Linux-6.2.0-26-generic-x86_64-with-glibc2.34
[2025-07-03T12:02:10.792+0000] {connection.py:1171} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-07-03T12:02:11.623+0000] {cursor.py:1028} INFO - query: [ALTER SESSION SET autocommit=False]
[2025-07-03T12:02:11.817+0000] {cursor.py:1041} INFO - query execution done
[2025-07-03T12:02:11.818+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2025-07-03T12:02:11.819+0000] {sql.py:450} INFO - Running statement: -- SELECT_QUERY_START
SELECT 
    PROJECT_ID, PROJECT_NAME, DEPARTMENT, START_DATE, END_DATE, BUDGET
FROM DEV_DB.DEV_SCHEMA.ATTENDANCE
WHERE START_DATE >= '2024-01-01'
ORDER BY START_DATE, parameters: None
[2025-07-03T12:02:11.819+0000] {cursor.py:1028} INFO - query: [-- SELECT_QUERY_START SELECT PROJECT_ID, PROJECT_NAME, DEPARTMENT, START_DATE, E...]
[2025-07-03T12:02:12.132+0000] {cursor.py:1041} INFO - query execution done
[2025-07-03T12:02:12.139+0000] {connection.py:718} INFO - closed
[2025-07-03T12:02:12.241+0000] {connection.py:724} INFO - No async queries seem to be running, deleting session
[2025-07-03T12:02:12.351+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/merge_query_dag.py", line 45, in merge_query
    hook.run(q)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 388, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 455, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 1132, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 000904 (42000): 01bd70d2-3201-c0df-000e-50720001f722: SQL compilation error: error line 2 at position 4
invalid identifier 'PROJECT_ID'
[2025-07-03T12:02:12.364+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=merge_query_to_temp_logs, task_id=run_merge_query, execution_date=20250703T120209, start_date=20250703T120210, end_date=20250703T120212
[2025-07-03T12:02:12.388+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 49 for task run_merge_query (000904 (42000): 01bd70d2-3201-c0df-000e-50720001f722: SQL compilation error: error line 2 at position 4
invalid identifier 'PROJECT_ID'; 9734)
[2025-07-03T12:02:12.434+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-03T12:02:12.461+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
