[2025-07-03T09:33:09.060+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: select_query_dag.run_select_query manual__2025-07-03T09:33:07.494433+00:00 [queued]>
[2025-07-03T09:33:09.066+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: select_query_dag.run_select_query manual__2025-07-03T09:33:07.494433+00:00 [queued]>
[2025-07-03T09:33:09.066+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-07-03T09:33:09.074+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_select_query> on 2025-07-03 09:33:07.494433+00:00
[2025-07-03T09:33:09.077+0000] {standard_task_runner.py:60} INFO - Started process 1027 to run task
[2025-07-03T09:33:09.079+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'select_query_dag', 'run_select_query', 'manual__2025-07-03T09:33:07.494433+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/select_query_dag.py', '--cfg-path', '/tmp/tmpkbpbff95']
[2025-07-03T09:33:09.080+0000] {standard_task_runner.py:88} INFO - Job 33: Subtask run_select_query
[2025-07-03T09:33:09.119+0000] {task_command.py:423} INFO - Running <TaskInstance: select_query_dag.run_select_query manual__2025-07-03T09:33:07.494433+00:00 [running]> on host be92b7fd988a
[2025-07-03T09:33:09.185+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='select_query_dag' AIRFLOW_CTX_TASK_ID='run_select_query' AIRFLOW_CTX_EXECUTION_DATE='2025-07-03T09:33:07.494433+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-03T09:33:07.494433+00:00'
[2025-07-03T09:33:09.186+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/select_query_dag.py", line 25, in select_query
    query = get_sql('/opt/airflow/scripts/sql/select.sql', context)
  File "/opt/airflow/dags/select_query_dag.py", line 19, in get_sql
    with open(file_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/sql/select.sql'
[2025-07-03T09:33:09.193+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=select_query_dag, task_id=run_select_query, execution_date=20250703T093307, start_date=20250703T093309, end_date=20250703T093309
[2025-07-03T09:33:09.210+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 33 for task run_select_query ([Errno 2] No such file or directory: '/opt/airflow/scripts/sql/select.sql'; 1027)
[2025-07-03T09:33:09.252+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-03T09:33:09.277+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
